### ISSUE TITLE
[Feature Request] Code Shrinking

### ISSUE THREAD

**Issue by Kylepoops** [TabooLib/taboolib-gradle-plugin#15]
Implement a code shrinking that removes all unused classes, methods and fields to decrease the jar size

**Comment by Bkm016** [comment]
taboolib-gradle-plugin 已经为 TabooLib 单独适配了体积压缩功能，并且无法通过 "unused classes" 来移除。
因为 TabooLib 包含太多拥有自动唤醒（Automatic awake）机制的类。
